class G3v2Effects(object):
    effects = {
        0: 'M-FILTER',
        1: 'THE VIBE',
        2: 'Z-ORGAN',
        3: 'PEDAL VX',
        4: 'PHASE DELAY',
        5: 'FILTER DELAY',
        6: 'PITCH DELAY',
        7: 'STEREO DELAY',
        8: 'BIT CRUSH',
        9: 'BOMBER',
        10: 'DUO-PHASE',
        11: 'MONOSYNTH',
        12: 'SEQ FILTER',
        13: 'RANDOM FLTR',
        14: 'WARP PHASER',
        15: 'TRIGGER HOLD DLY',
        16: 'CHOR+DLY',
        17: 'CHOR+REV',
        18: 'DLY+REV',
        19: 'COMP PHASER',
        20: 'COMP AWAH',
        21: 'FLANGER V-CHO',
        22: 'COMP OD',
        23: 'COMP',
        24: 'Rock COMP',
        25: 'M COMP',
        26: 'SLOW ATTACK',
        27: 'ZNR',
        28: 'NOISE GATE',
        29: 'DIRTY GATE',
        30: 'GRAPHIC EQ',
        31: 'PARA EQ',
        32: 'COMB FILTER',
        33: 'AUTO WAH',
        34: 'RESONANCE',
        35: 'STEP',
        36: 'CRY',
        37: 'OCTAVE',
        38: 'TREMOLO',
        39: 'PHASER',
        40: 'RING MOD',
        41: 'CHORUS',
        42: 'DETUNE',
        43: 'VINTAGE CE',
        44: 'STEREO CHORUS',
        45: 'ENSEMBLE',
        46: 'VINTAGE FLANGER',
        47: 'DYNO FLANGER',
        48: 'VIBRATO',
        49: 'PITH SHIFT',
        50: 'BEND CHORUS',
        51: 'MONO PITCH',
        52: 'HPS',
        53: 'DELAY',
        54: 'TAPE ECHO',
        55: 'MOD DELAY',
        56: 'ANALOG DELAY',
        57: 'REV. DLY',
        58: 'MULTI TAP DELAY',
        59: 'DYNA DELAY',
        60: 'HALL',
        61: 'ROOM',
        62: 'TILED ROOM',
        63: 'SPRING',
        64: 'ARENA REVERB',
        65: 'EARLY REFLECTION',
        66: 'AIR',
        67: 'PEDAL VX',
        68: 'PEDAL CRY',
        69: 'PEDAL PITCH',
        70: 'PEDAL MN PIT',
        71: 'BOOSTER',
        72: 'OVERDRIVE',
        73: 'TUBE SCREAM',
        74: 'GOVERNOR',
        75: 'DIST+',
        76: 'DIST 1',
        77: 'SQUEAK',
        78: 'FUZZ SMILE',
        79: 'GREAT MUFF',
        80: 'METAL WORLD',
        81: 'HOTBOX',
        82: 'Z WILD',
        83: 'LEAD ZOOM9002',
        84: 'EXTREME DIST',
        85: 'ACOUSTIC',
        86: 'Z CLEAN',
        87: 'Z MP1',
        88: 'BOTTOM',
        89: 'Z DREAM',
        90: 'Z SCREAM',
        91: 'Z NEOS',
        92: 'FD COMBO',
        93: 'VX COMBO',
        94: 'US BLUES',
        95: 'BG CRUNCH',
        96: 'HW STACK',
        97: 'TANGERINE',
        98: 'MS CRUNCH',
        99: 'MS DRIVE0',
        100: 'BG DRIVE1',
        101: 'DZ DRIVE2',
        102: 'TW ROCK3',
        103: 'MATCH304',
        104: 'FD VIBRO5',
        105: 'HD REVERB',
        106: 'FLANGER',
        107: '---',
    }
