
guitar_amp_cabinet = {
    8: 'FD COMBO 2x12',
    16: 'DLX-R 1x12',
    32: 'FD VIBRO 2x10',
    48: 'US BLUES 4x10',
    64: 'VX COMBO 2x12',
    80: 'VX JMI 2x12',
    96: 'BG CRUNCH 1x12',
    112: 'MATCH 30 2x12',
    128: 'CAR DRIVE 1x12',
    144: 'TW ROCK 1x12',
    160: 'TONE CITY 4x12',
    176: 'HW STACK 4x12',
    192: 'TANGERINE 4x12',
    208: 'B-BRKR 2x12',
    224: 'MS CRUNCH 4x12',
    240: 'MS 1959 4x12',
    256: 'MS DRIVE 4x12',
    272: 'BGN DRIVE 4x12',
    288: 'BG DRIVE 4x12',
    304: 'DZ DRIVE 4x12',
    320: 'ALIEN 4x12',
    336: 'REVO-1 4x12',
    0: 'OFF'
}

bampcabmax = []
bampcabdisp = []

guitar_amp_values = guitar_amp_cabinet.keys()
guitar_amp_max = max(guitar_amp_values)
guitar_amp_labels = guitar_amp_cabinet


# https://www.zikinf.com/manuels/zoom-g1on-liste-des-effets-et-parametres-en-46322.pdf
effectlist = {
    0x00100002: {'name': "Comp", 'category': "COMP", 'order': 0, 'install': 0, 'ver': 0x0201,
                 'title': "This compressor in the style of the MXR Dyna Comp",
                 #'dsp': 14.2979, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Sense", 'default': 6, 'max': 10},
                     {'name': "Tone", 'default': 6, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "ATTCK", 'default': 0, 'max': 1, 'labels': ["Slow", "Fast"]}
                 ]},
    0x00600002: {'name': "OptComp", 'category': "COMP", 'order': 1, 'install': 0, 'ver': 0x0212,
                 'title': "This compressor is in the style of an APHEX Punch FACTORY",
                 #'dsp': 7.5045, 'dspmax': 1 / 6, 'dspmin': 16 / 100,
                 'parameters': [
                     {'name': "Drive", 'default': 7, 'max': 10},
                     {'name': "Tone", 'default': 54, 'max': 100},
                     {'name': "Level", 'default': 50, 'max': 150}
                 ]},
    0x006a0002: {'name': "160 Comp", 'category': "COMP", 'order': 2, 'install': 0, 'ver': 0x0210,
                 'title': "This compressor is in the style of the dbx 160A",
                 #'dsp': 7.2000, 'dspmax': 1 / 6, 'dspmin': 16 / 100,
                 'parameters': [
                     {'name': "THRSH", 'default': 38, 'max': 60, 'disp': -60},
                     {'name': "Ratio", 'default': 30, 'max': 90, 'disp': 1, 'dispr': 0.1},
                     {'name': "Gain", 'default': 6, 'max': 20},
                     {'name': "Knee", 'default': 0, 'max': 1, 'labels': ["Hard", "Soft"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
    0x40000002: {'name': "SlowATTCK", 'category': "COMP", 'order': 3, 'install': 0, 'ver': 0x0211,
                 'title': "This effect slows the attack of each note, resulting in a violin-like performance",
                 #'dsp': 12.0646, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Time", 'default': 20, 'max': 49, 'disp': 1},
                     {'name': "Curve", 'default': 10, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x40200002: {'name': "ZNR", 'category': "COMP", 'order': 4, 'install': 0, 'ver': 0x0111,
                 'title': "ZOOM's unique noise reduction cuts noise during pauses in playing without affecting the tone",
                 #'dsp': 17.4545, 'dspmax': 1 / 12, 'dspmin': 1 / 30,
                 'parameters': [
                     {'name': "THRSH", 'default': 9, 'max': 24, 'disp': 1},
                     {'name': "DETCT", 'default': 1, 'max': 1, 'labels': ["GtrIn", "EfxIn"]},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40400002: {'name': "NoiseGate", 'category': "COMP", 'order': 5, 'install': 0, 'ver': 0x0222,
                 #'title': "This is a noise gate that cuts the sound during playing pauses",
                 #'dsp': 14.1548, 'dspmax': 1 / 12, 'dspmin': 1 / 30,
                 'parameters': [
                     {'name': "THRSH", 'default': 9, 'max': 24, 'disp': 1},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00200004: {'name': "GraphicEQ", 'category': "FILTER", 'order': 6, 'install': 0, 'ver': 0x0201,
                 #'title': "This unit has a 6 band equalizer",
                 #'dsp': 11.6667, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "160Hz", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "400Hz", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "800Hz", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "3.2kHz", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "6.4kHz", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "12kHz", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x00400004: {'name': "ParaEQ", 'category': "FILTER", 'order': 7, 'install': 0, 'ver': 0x0201,
                 'title': "This is a 2-band parametric equalizer",
                 #'dsp': 16.0000, 'dspmax': 1 / 12, 'dspmin': 1 / 30,
                 'parameters': [
                     {'name': "Freq1", 'default': 8, 'max': 30,
                      'labels': ["20Hz", "25Hz", "32Hz", "40Hz", "50Hz", "63Hz", "80Hz", "100Hz", "125Hz", "160Hz",
                               "200Hz", "250Hz", "320Hz", "400Hz", "500Hz", "630Hz",
                               "800Hz", "1.0kHz", "1.2kHz", "1.6kHz", "2.0kHz", "2.5kHz", "3.2kHz", "4.0kHz", "5.0kHz",
                               "6.3kHz", "8.0kHz", "10kHz", "12kHz", "16kHz", "20kHz"]},
                     {'name': "Q1", 'default': 1, 'max': 5, 'labels': ["0.5", "1", "2", "4", "8", "16"]},
                     {'name': "Gain1", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "Freq2", 'default': 15, 'max': 30,
                      'labels': ["20Hz", "25Hz", "32Hz", "40Hz", "50Hz", "63Hz", "80Hz", "100Hz", "125Hz", "160Hz",
                               "200Hz", "250Hz", "320Hz", "400Hz", "500Hz", "630Hz",
                               "800Hz", "1.0kHz", "1.2kHz", "1.6kHz", "2.0kHz", "2.5kHz", "3.2kHz", "4.0kHz", "5.0kHz",
                               "6.3kHz", "8.0kHz", "10kHz", "12kHz", "16kHz", "20kHz"]},
                     {'name': "Q2", 'default': 1, 'max': 5, 'labels': ["0.5", "1", "2", "4", "8", "16"]},
                     {'name': "Gain2", 'default': 12, 'max': 24, 'disp': -12},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00600004: {'name': "Exciter", 'category': "FILTER", 'order': 8, 'install': 0, 'ver': 0x0212,
                 'title': "2-band phase exciter",
                 #'dsp': 11.8597, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Bass", 'default': 0, 'max': 100},
                     {'name': "Trebl", 'default': 0, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x40200004: {'name': "AutoWah", 'category': "FILTER", 'order': 9, 'install': 0, 'ver': 0x0201,
                 'title': "This effect varies wah in accordance with picking intensity",
                 #'dsp': 10.1045, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Sense", 'default': 17, 'max': 19,
                      'labels': ["-10", "-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "1", "2", "3", "4", "5",
                               "6", "7", "8", "9", "10"]},
                     {'name': "Reso", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x40600004: {'name': "Cry", 'category': "FILTER", 'order': 10, 'install': 0, 'ver': 0x0201,
                 'title': "This effect varies the sound like a talking modulator",
                 #'dsp': 11.9290, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Range", 'default': 6, 'max': 9, 'disp': 1},
                     {'name': "Reso", 'default': 8, 'max': 10},
                     {'name': "Sense", 'default': 16, 'max': 19,
                      'labels': ["-10", "-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "1", "2", "3", "4", "5",
                               "6", "7", "8", "9", "10"]},
                     {'name': "Bal", 'default': 100, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}]},
0x00200104: {'name': "M-Filter", 'category': "FILTER", 'order': 11, 'install': 0, 'ver': 0x0211,
                 'title': "This envelope filter has the flavor of a MOOG MF-101 Low Pass Filter and can be set in a wide range",
                 #'dsp': 8.0000, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Freq", 'default': 56, 'max': 100},
                     {'name': "Sense", 'default': 5, 'max': 10},
                     {'name': "Reso", 'default': 7, 'max': 10},
                     {'name': "Type", 'default': 2, 'max': 2, 'labels': ["HPF", "BPF", "LPF"]},
                     {'name': "Chara", 'default': 1, 'max': 1, 'labels': ["2Pole", "4Pole"]},
                     {'name': "VLCTY", 'default': 0, 'max': 1, 'labels': ["Fast", "Slow"]},
                     {'name': "Bal", 'default': 100, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00400104: {'name': "Step", 'category': "FILTER", 'order': 12, 'install': 0, 'ver': 0x0201,
                 'title': "This special effect gives the sound a stepped quality",
                 #'dsp': 11.2783, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Depth", 'default': 60, 'max': 100},
                     {'name': "Rate", 'default': 25, 'max': 78},  # FIXME - Add time labels
                     {'name': "Reso", 'default': 8, 'max': 10},
                     {'name': "Shape", 'default': 10, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00600104: {'name': "SeqFLTR", 'category': "FILTER", 'order': 13, 'install': 0, 'ver': 0x0211,
                 'title': "The sequence filter has the flavor of a Z.Vex Seek-Wah",
                 #'dsp': 9.6000, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Step", 'default': 6, 'max': 6, 'disp': 2},
                     {'name': "PTTRN", 'default': 6, 'max': 7, 'disp': 1},
                     {'name': "Speed", 'default': 25, 'max': 77, 'disp': 1},  # FIXME - Add time labels
                     {'name': "Shape", 'default': 10, 'max': 10},
                     {'name': "Reso", 'default': 10, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40000104: {'name': "RndmFLTR", 'category': "FILTER", 'order': 14, 'install': 0, 'ver': 0x0222,
                 'title': "This filter effect changes character randomly",
                 #'dsp': 9.6000, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Speed", 'default': 34, 'max': 77, 'disp': 1},  # FIXME - Add time labels
                     {'name': "Range", 'default': 50, 'max': 100},
                     {'name': "Reso", 'default': 6, 'max': 10},
                     {'name': "Type", 'default': 2, 'max': 2, 'labels': ["HPF", "BPF", "LPF"]},
                     {'name': "Chara", 'default': 1, 'max': 1, 'labels': ["2Pole", "4Pole"]},
                     {'name': "Bal", 'default': 90, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40200104: {'name': "fCycle", 'category': "FILTER", 'order': 15, 'install': 0, 'ver': 0x0222,
                 'title': "This filter effect changes tone characteristics cyclically",
                 #'dsp': 10.1045, 'dspmax': 1 / 10, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Rate", 'default': 5, 'max': 77, 'disp': 1}, # FIXME - Add time labels
                     {'name': "Wave", 'default': 3, 'max': 3, 'labels': ["Sine", "Tri", "SawUp", "SawDn"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Depth", 'default': 100, 'max': 100},
                     {'name': "Reso", 'default': 8, 'max': 10}
                 ]},
0x00100006: {'name': "Booster", 'category': "DRIVE", 'order': 16, 'install': 0, 'ver': 0x0001,
                 'title': "The booster increases signal gain to make the sound more powerful",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 80, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x00200006: {'name': "OverDrive", 'category': "DRIVE", 'order': 17, 'install': 0, 'ver': 0x0001,
                 'title': 'Simulation of the BOSS OD-1, the compact effect box that was the first to take the "overdrive" title',
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x00400006: {'name': "T Scream", 'category': "DRIVE", 'order': 18, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the Ibanez TS808, which is loved by many guitarists as a booster and has inspired numerous clones",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 70, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
0x00600006: {'name': "Governor", 'category': "DRIVE", 'order': 19, 'install': 0, 'ver': 0x0002,
                 'title': "Simulation of the Guv'nor distortion effect from Marshall",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40000006: {'name': "Dist+", 'category': "DRIVE", 'order': 20, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the MXR distortion+ effect that made distortion popular worldwide",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 80, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40200006: {'name': "Dist 1", 'category': "DRIVE", 'order': 21, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the BOSS DS-1 distortion pedal, which has been a long-seller",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40400006: {'name': "Squeak", 'category': "DRIVE", 'order': 22, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the popular Pro Co RAT famous for its edgy distortion sound",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 40, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40600006: {'name': "FuzzSmile", 'category': "DRIVE", 'order': 23, 'install': 0, 'ver': 0x0002,
                 'title': "Simulation of the Fuzz Face, which has made rock history with its humorous panel design and smashing sound",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 70, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00000106: {'name': "GreatMuff", 'category': "DRIVE", 'order': 24, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the Electro-Harmonix Big Muff, which is loved by famous artists around the world for its fat, sweet fuzz sound",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 70, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00200106: {'name': "MetalWRLD", 'category': "DRIVE", 'order': 25, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the BOSS Metal Zone, which is characterized by long sustain and a powerful lower midrange",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00400106: {'name': "HotBox", 'category': "DRIVE", 'order': 26, 'install': 0, 'ver': 0x0001,
                 'title': "Simulation of the compact MATCHLESS HOT BOX pre-amplifier with a built-in tube",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00600106: {'name': "Z Clean", 'category': "DRIVE", 'order': 27, 'install': 0, 'ver': 0x0001,
                 'title': "ZOOM original unadorned clean sound",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40000106: {'name': "Z MP1", 'category': "DRIVE", 'order': 28, 'install': 0, 'ver': 0x0002,
                 'title': "An original sound created by merging characteristics of an ADA MP1 and a Marshall JCM800",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40600106: {'name': "Z Scream", 'category': "DRIVE", 'order': 29, 'install': 0, 'ver': 0x0002,
                 'title': "An original high gain sound balanced from low to high frequencies",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00200206: {'name': "Z Wild", 'category': "DRIVE", 'order': 30, 'install': 0, 'ver': 0x0002,
                 'title': "A high gain sound with even more overdrive boost",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00400206: {'name': "Lead", 'category': "DRIVE", 'order': 31, 'install': 0, 'ver': 0x0002,
                 'title': "Lead a bright and smooth distortion sound",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00600206: {'name': "ExtremeDS", 'category': "DRIVE", 'order': 32, 'install': 0, 'ver': 0x0001,
                 'title': "This distortion effect boasts the highest gain in the world",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Gain", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x40000206: {'name': "Aco.Sim", 'category': "DRIVE", 'order': 33, 'install': 0, 'ver': 0x0001,
                 'title': "This effect changes the tone of an electric guitar to make it sound like an acoustic guitar",
                 #'dsp': 7.9892, 'dspmax': 1 / 6, 'dspmin': 1 / 10,
                 'parameters': [
                     {'name': "Top", 'default': 80, 'max': 100},
                     {'name': "Body", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150}
                 ]},
    0x00100008: {'name': "FD COMBO", 'category': "AMP", 'order': 34, 'install': 0, 'ver': 0x0001,
                 'title': "Modeled sound of a Fender Twin Reverb ('65), which is loved by guitarists in various genres",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 24, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 86, 'max': 150},
                     {'name': "Trebl", 'default': 48, 'max': 100},
                     {'name': "Middl", 'default': 45, 'max': 100},
                     {'name': "Bass", 'default': 44, 'max': 100},
                     {'name': "Prese", 'default': 52, 'max': 100},
                     {'name': "CAB", 'default': 8, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}
                 ]},
    0x00200008: {'name': "DELUXE-R", 'category': "AMP", 'order': 35, 'install': 0, 'ver': 0x0001,
                 'title': "This models the sound of a Fender Deluxe Reverb made in 1965",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 50, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 50, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 16, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}
                 ]},
    0x00400008: {'name': "FD VIBRO", 'category': "AMP", 'order': 36, 'install': 0, 'ver': 0x0003,
                 'title': "Modeled sound of a '63 Fender Vibroverb",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 56, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 98, 'max': 150},
                     {'name': "Trebl", 'default': 54, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 47, 'max': 100},
                     {'name': "Prese", 'default': 52, 'max': 100},
                     {'name': "CAB", 'default': 32, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}
                 ]},
    0x00600008: {'name': "US BLUES", 'category': "AMP", 'order': 37, 'install': 0, 'ver': 0x0001,
                 'title': "Crunch sound of a Fender Tweed Bassman",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 59, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 107, 'max': 150},
                     {'name': "Trebl", 'default': 46, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 48, 'max': 100},
                     {'name': "Prese", 'default': 58, 'max': 100},
                     {'name': "CAB", 'default': 48, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40000008: {'name': "VX COMBO", 'category': "AMP", 'order': 38, 'install': 0, 'ver': 0x0003,
                 'title': "Modeled sound of a British combo amplifier representing the 1960s Liverpool sound",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 31, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Trebl", 'default': 44, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 49, 'max': 100},
                     {'name': "Prese", 'default': 53, 'max': 100},
                     {'name': "CAB", 'default': 64, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40200008: {'name': "VX JMI", 'category': "AMP", 'order': 39, 'install': 0, 'ver': 0x0001,
                 'title': "This simulates the sound of an early model of a class-A British combo amp",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 50, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 50, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 80, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4, 'labels': [
                         "LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40400008: {'name': "BG CRUNCH", 'category': "AMP", 'order': 40, 'install': 0, 'ver': 0x0003,
                 'title': "Crunch sound of a Mesa Boogie MkIII combo amp",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 57, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 99, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 50, 'max': 100},
                     {'name': "Prese", 'default': 60, 'max': 100},
                     {'name': "CAB", 'default': 96, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40600008: {'name': "MATCH 30", 'category': "AMP", 'order': 41, 'install': 0, 'ver': 0x0003,
                 'title': "Modeled sound of a DC-30 (channel 1), the Matchless flagship combo amp",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 28, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Trebl", 'default': 46, 'max': 100},
                     {'name': "Middl", 'default': 46, 'max': 100},
                     {'name': "Bass", 'default': 45, 'max': 100},
                     {'name': "Prese", 'default': 53, 'max': 100},
                     {'name': "CAB", 'default': 112, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00000108: {'name': "CAR DRIVE", 'category': "AMP", 'order': 42, 'install': 0, 'ver': 0x0003,
                 'title': "This models the sound of a Carr Mercury high-end small combo amp",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 51, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 74, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 50, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 128, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00200108: {'name': "TW ROCK", 'category': "AMP", 'order': 43, 'install': 0, 'ver': 0x0001,
                 'title': "This crunch sound uses the drive channel of a Two Rock Emerald 50, an American boutique amplifier",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 53, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 95, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 51, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 144, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00400108: {'name': "TONE CITY", 'category': "AMP", 'order': 44, 'install': 0, 'ver': 0x0003,
                 'title': "This models the sound of a Sound City 50 Plus Mark 2, a legendary British amplifier",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 78, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 89, 'max': 150},
                     {'name': "Trebl", 'default': 54, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 46, 'max': 100},
                     {'name': "Prese", 'default': 52, 'max': 100},
                     {'name': "CAB", 'default': 160, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00600108: {'name': "HW STACK", 'category': "AMP", 'order': 45, 'install': 0, 'ver': 0x0003,
                 'title': "Modeled sound of the legendary Hiwatt Custom 100 all-tube amplifier from the UK",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 54, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 106, 'max': 150},
                     {'name': "Trebl", 'default': 46, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 56, 'max': 100},
                     {'name': "Prese", 'default': 52, 'max': 100},
                     {'name': "CAB", 'default': 176, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40000108: {'name': "TANGERINE", 'category': "AMP", 'order': 46, 'install': 0, 'ver': 0x0003,
                 'title': "This models the Orange Graphic 120 with its unique design and sound",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 70, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 99, 'max': 150},
                     {'name': "Trebl", 'default': 52, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 45, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 192, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40200108: {'name': "B-BREAKER", 'category': "AMP", 'order': 47, 'install': 0, 'ver': 0x0003,
                 'title': "This models the sound of a Marshall 1962 Bluesbreaker combo amp",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 61, 'max': 100},
                     {'name': "Tube", 'default': 31, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 52, 'max': 100},
                     {'name': "Prese", 'default': 51, 'max': 100},
                     {'name': "CAB", 'default': 208, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40400108: {'name': "MS CRUNCH", 'category': "AMP", 'order': 48, 'install': 0, 'ver': 0x0003,
                 'title': "The crunch sound of the Marshall 1959 that has given birth to many legends",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 72, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 98, 'max': 150},
                     {'name': "Trebl", 'default': 46, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 53, 'max': 100},
                     {'name': "Prese", 'default': 54, 'max': 100},
                     {'name': "CAB", 'default': 224, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40600108: {'name': "MS 1959", 'category': "AMP", 'order': 49, 'install': 0, 'ver': 0x0001,
                 'title': "This models the sound of a Marshall 1959 Plexi made in 1969",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 58, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 50, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 240, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00000208: {'name': "MS DRIVE", 'category': "AMP", 'order': 50, 'install': 0, 'ver': 0x0003,
                 'title': "The high gain sound of a JCM2000 Marshall stack amp",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 82, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 103, 'max': 150},
                     {'name': "Trebl", 'default': 45, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 56, 'max': 100},
                     {'name': "Prese", 'default': 53, 'max': 100},
                     {'name': "CAB", 'default': 256, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00200208: {'name': "BGN DRIVE", 'category': "AMP", 'order': 51, 'install': 0, 'ver': 0x0003,
                 'title': "This simulates the lead sound from channel 3 of a Bogner Ecstasy",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 84, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 91, 'max': 150},
                     {'name': "Trebl", 'default': 52, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 49, 'max': 100},
                     {'name': "Prese", 'default': 50, 'max': 100},
                     {'name': "CAB", 'default': 272, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00400208: {'name': "BG DRIVE", 'category': "AMP", 'order': 52, 'install': 0, 'ver': 0x0003,
                 'title': "The high gain sound of the Mesa Boogie Dual Rectifier red channel (Vintage mode)",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 47, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 97, 'max': 150},
                     {'name': "Trebl", 'default': 48, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 52, 'max': 100},
                     {'name': "Prese", 'default': 48, 'max': 100},
                     {'name': "CAB", 'default': 288, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x00600208: {'name': "DZ DRIVE", 'category': "AMP", 'order': 53, 'install': 0, 'ver': 0x0001,
                 'title': "The 3-channel high gain sound of a Diezel Herbert, which is a handmade German guitar amplifier that allows control of three independent channels",
                 #'dsp': 3.1102, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "Gain", 'default': 45, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 93, 'max': 150},
                     {'name': "Trebl", 'default': 53, 'max': 100},
                     {'name': "Middl", 'default': 47, 'max': 100},
                     {'name': "Bass", 'default': 51, 'max': 100},
                     {'name': "Prese", 'default': 55, 'max': 100},
                     {'name': "CAB", 'default': 304, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40000208: {'name': "ALIEN", 'category': "AMP", 'order': 54, 'install': 0, 'ver': 0x0001,
                 'title': "This simulates the high-gain sound of the Engl Invader, which features a powerful low-end",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 62, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 87, 'max': 150},
                     {'name': "Trebl", 'default': 52, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 44, 'max': 100},
                     {'name': "Prese", 'default': 54, 'max': 100},
                     {'name': "CAB", 'default': 320, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x40200208: {'name': "REVO-1", 'category': "AMP", 'order': 55, 'install': 0, 'ver': 0x0003,
                 'title': "This simulates the high-gain sound of a Krank Revolution 1 Plus",
                 #'dsp': 2.3404, 'dspmax': 41 / 100, 'dspmin': 547 / 1500,
                 'parameters': [
                     {'name': "Gain", 'default': 64, 'max': 100},
                     {'name': "Tube", 'default': 30, 'max': 100},
                     {'name': "Level", 'default': 89, 'max': 150},
                     {'name': "Trebl", 'default': 50, 'max': 100},
                     {'name': "Middl", 'default': 50, 'max': 100},
                     {'name': "Bass", 'default': 51, 'max': 100},
                     {'name': "Prese", 'default': 51, 'max': 100},
                     {'name': "CAB", 'default': 336, 'max': guitar_amp_max, 'values': guitar_amp_values, 'labels': guitar_amp_labels},
                     {'name': "OUT", 'default': 0, 'max': 4,
                      'labels': ["LINE", "COMBO FRONT", "STACK FRONT", "COMBO POWER AMP", "STACK POWER AMP", ]}]},
    0x0010000c: {'name': "Tremolo", 'category': "MOD", 'order': 56, 'install': 0, 'ver': 0x0211,
                 'title': "This effect varies the volume at a regular rate",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Depth", 'default': 80, 'max': 100},
                     {'name': "Rate", 'default': 33, 'max': 78},  # FIXME - Add time labels
                     {'name': "Level", 'default': 130, 'max': 150},
                     {'name': "Wave", 'default': 21, 'max': 29,
                      'labels': ["UP 0", "UP 1", "UP 2", "UP 3", "UP 4", "UP 5", "UP 6", "UP 7", "UP 8", "UP 9",
                                 "DWN 0", "DWN 1", "DWN 2", "DWN 3", "DWN 4", "DWN 5", "DWN 6", "DWN 7", "DWN 8",
                                 "DWN 9",
                                 "TRI 0", "TRI 1", "TRI 2", "TRI 3", "TRI 4", "TRI 5", "TRI 6", "TRI 7", "TRI 8",
                                 "TRI 9"]}]},
    0x0040000c: {'name': "Slicer", 'category': "MOD", 'order': 57, 'install': 0, 'ver': 0x0202,
                 'title': "This effect creates a rhythmical sound by continuously slicing the input",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "PTTRN", 'default': 0, 'max': 19, 'disp': 1},
                     {'name': "Speed", 'default': 24, 'max': 77, 'disp': 1},
                     {'name': "Bal", 'default': 100, 'max': 100},
                     {'name': "THRSH", 'default': 20, 'max': 50},
                     {'name': "Level", 'default': 130, 'max': 150},
                 ]},
    0x0060000c: {'name': "Phaser", 'category': "MOD", 'order': 58, 'install': 0, 'ver': 0x0111,
                 'title': "This effect adds a phasing variation to the sound",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Rate", 'default': 11, 'max': 77, 'disp': 1},  # FIXME - Add time labels
                     {'name': "Color", 'default': 3, 'max': 3, 'labels': ["4 STG", "8 STG", "inv 4", "inv 8"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
    0x006a000c: {'name': "DuoPhase", 'category': "MOD", 'order': 59, 'install': 0, 'ver': 0x0221,
                 'title': "This effect combines 2 phasers",
                 #'dsp': 9.4118, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "RateA", 'default': 46, 'max': 77, 'disp': 1},  # FIXME - Add time labels
                     {'name': "RateB", 'default': 5, 'max': 51, 'disp': 1},  # FIXME - SncA, RvrsA labels
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "ResoA", 'default': 0, 'max': 10},
                     {'name': "ResoB", 'default': 6, 'max': 10},
                     {'name': "Link", 'default': 0, 'max': 2, 'labels': ["Seri", "Para", "STR"]},
                     {'name': "DPT_A", 'default': 36, 'max': 99, 'disp': 1},
                     {'name': "DPT_B", 'default': 62, 'max': 99, 'disp': 1},
                 ]},
    0x0000020c: {'name': "Vibrato", 'category': "MOD", 'order': 60, 'install': 0, 'ver': 0x0121,
                 'title': "This effect automatically adds vibrato",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Depth", 'default': 40, 'max': 100},
                     {'name': "Rate", 'default': 30, 'max': 78},  # FIXME - Add time labels
                     {'name': "Bal", 'default': 72, 'max': 100},
                     {'name': "Tone", 'default': 7, 'max': 10},
                     {'name': "Level", 'default': 120, 'max': 150},
                 ]},
    0x4000000c: {'name': "TheVibe", 'category': "MOD", 'order': 61, 'install': 0, 'ver': 0x0121,
                 'title': "This vibe sound features unique undulations",
                 #'dsp': 9.4118, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Speed", 'default': 25, 'max': 50},
                     {'name': "Depth", 'default': 60, 'max': 100},
                     {'name': "Bias", 'default': 48, 'max': 100},
                     {'name': "Wave", 'default': 24, 'max': 100},
                     {'name': "Mode", 'default': 1, 'max': 1, 'labels': ["VIBRT", "CHORS"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x0000010c: {'name': "Detune", 'category': "MOD", 'order': 62, 'install': 0, 'ver': 0x0101,
                 'title': "By mixing an effect sound that is slightly pitch-shifted with the original sound, this effect type has a chorus effect without much sense of modulation",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Cent", 'default': 35, 'max': 50, 'disp': -25},
                     {'name': "PreD", 'default': 0, 'max': 50},
                     {'name': "Mix", 'default': 52, 'max': 100},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4060000c: {'name': "Chorus", 'category': "MOD", 'order': 63, 'install': 0, 'ver': 0x0101,
                 'title': "This effect mixes a shifted pitch with the original sound to add movement and thickness",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 12,
                 'parameters': [
                     {'name': "Depth", 'default': 40, 'max': 100},
                     {'name': "Rate", 'default': 24, 'max': 49, 'disp': 1},
                     {'name': "Mix", 'default': 50, 'max': 100},
                     {'name': "Tone", 'default': 7, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x0040010c: {'name': "StereoCho", 'category': "MOD", 'order': 64, 'install': 0, 'ver': 0x0121,
                 'title': "This is a stereo chorus with a clear tone",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Depth", 'default': 80, 'max': 100},
                     {'name': "Rate", 'default': 29, 'max': 49, 'disp': 1},
                     {'name': "Mix", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 7, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x0060010c: {'name': "Ensemble", 'category': "MOD", 'order': 65, 'install': 0, 'ver': 0x0102,
                 'title': "This is a chorus ensemble that features three-dimensional movement",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Depth", 'default': 40, 'max': 100},
                     {'name': "Rate", 'default': 29, 'max': 49, 'disp': 1},
                     {'name': "Mix", 'default': 60, 'max': 100},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4020010c: {'name': "SuperCho", 'category': "MOD", 'order': 66, 'install': 0, 'ver': 0x0121,
                 'title': "This models the sound of a BOSS CH-1 SUPER CHORUS",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "E.LVL", 'default': 50, 'max': 120},
                     {'name': "Rate", 'default': 50, 'max': 100},
                     {'name': "Depth", 'default': 50, 'max': 100},
                     {'name': "EQ", 'default': 50, 'max': 100},
                     {'name': "Mode", 'default': 0, 'max': 1, 'labels': ["MONO", "STR"]},
                 ]},
0x0000040c: {'name': "CoronaTri", 'category': "MOD", 'order': 67, 'install': 0, 'ver': 0x0123,
                 'title': "This is a model of tc electronic's CORONA Tri-Chorus",
                 #'dsp': 3.6923, 'dspmax': 1 / 3, 'dspmin': 1 / 4,
                 'parameters': [
                     {'name': "SPEED", 'default': 25, 'max': 100},
                     {'name': "DEPTH", 'default': 100, 'max': 100},
                     {'name': "FxLVL", 'default': 100, 'max': 100},
                     {'name': "TONE", 'default': 100, 'max': 100},
                     {'name': "DRY", 'default': 1, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x4040010c: {'name': "Flanger", 'category': "MOD", 'order': 68, 'install': 0, 'ver': 0x0101,
                 'title': "This is a jet sound like an ADA Flanger",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Depth", 'default': 47, 'max': 100},
                     {'name': "Rate", 'default': 7, 'max': 78},
                     {'name': "Reso", 'default': 18, 'max': 20, 'disp': -10},
                     {'name': "PreD", 'default': 4, 'max': 50},
                     {'name': "Mix", 'default': 65, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4030010c: {'name': "VinFLNGR", 'category': "MOD", 'order': 69, 'install': 0, 'ver': 0x0222,
                 'title': "This analog flanger sound is similar to an MXR M-117R",
                 #'dsp': 12.4737, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Depth", 'default': 47, 'max': 100},
                     {'name': "Rate", 'default': 7, 'max': 78},  # FIXME - Add time labels
                     {'name': "Reso", 'default': 18, 'max': 20, 'disp': -10},
                     {'name': "PreD", 'default': 4, 'max': 50},
                     {'name': "Mix", 'default': 65, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x0020020c: {'name': "Octave", 'category': "MOD", 'order': 70, 'install': 0, 'ver': 0x0201,
                 'title': "This effect adds sound one octave and two octaves below the original sound",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Oct1", 'default': 80, 'max': 100},
                     {'name': "Oct2", 'default': 15, 'max': 100},
                     {'name': "Dry", 'default': 100, 'max': 100},
                     {'name': "Chara", 'default': 100, 'max': 100},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x0040020c: {'name': "PitchSHFT", 'category': "MOD", 'order': 71, 'install': 0, 'ver': 0x0111,
                 'title': "This effect shifts the pitch up or down",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Shift", 'default': 19, 'max': 25,
                      'labels': ["-12", "-11", "-10", "-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "0", "1", "2",
                               "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "24"]},
                     {'name': "Tone", 'default': 7, 'max': 10},
                     {'name': "Bal", 'default': 40, 'max': 100},
                     {'name': "Fine", 'default': 25, 'max': 50, 'disp': -25},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
    0x0060020c: {'name': "MonoPitch", 'category': "MOD", 'order': 72, 'install': 0, 'ver': 0x0201,
                 'title': "This is a pitch shifter with little sound variance for monophonic (single note) playing",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Shift", 'default': 0, 'max': 25, 'disp': -12,
                      'labels': ["-12", "-11", "-10", "-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "0", "1", "2",
                               "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "24"]},
                     {'name': "Tone", 'default': 6, 'max': 10},
                     {'name': "Bal", 'default': 50, 'max': 100},
                     {'name': "Fine", 'default': 25, 'max': 50, 'disp': -25},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4000020c: {'name': "HPS", 'category': "MOD", 'order': 73, 'install': 0, 'ver': 0x0101,
                 'title': "This intelligent pitch shifter outputs the effect sound with the pitch shifted according to scale and key settings",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Scale", 'default': 6, 'max': 9,
                      'labels': ["-6", "-5", "-4", "-3", "-m", "m", "3", "4", "5", "6"]},
                     {'name': "Key", 'default': 0, 'max': 11,
                      'labels': ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]},
                     {'name': "Mix", 'default': 70, 'max': 100},
                     {'name': "Tone", 'default': 6, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4020020c: {'name': "BendCho", 'category': "MOD", 'order': 74, 'install': 0, 'ver': 0x0202,
                 'title': "This effect provides pitch bending that uses the input signal as trigger and processes each note separately",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Depth", 'default': 40, 'max': 100},
                     {'name': "Time", 'default': 50, 'max': 50},
                     {'name': "Bal", 'default': 100, 'max': 100},
                     {'name': "Mode", 'default': 0, 'max': 1, 'labels': ["Up", "Down"]},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4060020c: {'name': "RingMod", 'category': "MOD", 'order': 75, 'install': 0, 'ver': 0x0222,
                 'title': "This effect produces a metallic ringing sound. Adjusting the “Freq” parameter results in a drastic change of sound character",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Freq", 'default': 27, 'max': 49, 'disp': 1},
                     {'name': "Tone", 'default': 10, 'max': 10},
                     {'name': "Bal", 'default': 50, 'max': 100},
                     {'name': "Level", 'default': 120, 'max': 150},
                 ]},
0x4040000e: {'name': "Rt Closet", 'category': "SFX", 'order': 76, 'install': 0, 'ver': 0x0122,
                 'title': "Simulates a rotary speaker",
                 #'dsp': 4.4444, 'dspmax': 1 / 4, 'dspmin': 1 / 5,
                 'parameters': [
                     {'name': "Bal", 'default': 50, 'max': 100},
                     {'name': "Mode", 'default': 0, 'max': 1, 'labels': ["Slow", "Fast"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Drive", 'default': 20, 'max': 100},
                 ]},
0x0020000e: {'name': "BitCrush", 'category': "SFX", 'order': 77, 'install': 0, 'ver': 0x0222,
                 'title': "This effect creates a lo-fi sound",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Bit", 'default': 5, 'max': 12, 'disp': 4},
                     {'name': "SMPL", 'default': 2, 'max': 50},
                     {'name': "Bal", 'default': 90, 'max': 100},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
    0x0040000e: {'name': "Bomber", 'category': "SFX", 'order': 78, 'install': 0, 'ver': 0x0222,
                 'title': "This effect produces an explosive sound when picking",
                 #'dsp': 10.7911, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "PTTRN", 'default': 3, 'max': 3, 'labels': ["HndGn", "Arm", "Bomb", "Thndr"]},
                     {'name': "Deay", 'default': 49, 'max': 99, 'disp': 1},
                     {'name': "Bal", 'default': 15, 'max': 100},
                     {'name': "THRSH", 'default': 40, 'max': 50},
                     {'name': "Power", 'default': 30, 'max': 30},
                     {'name': "Tone", 'default': 4, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x4000000e: {'name': "Z-Organ", 'category': "SFX", 'order': 79, 'install': 0, 'ver': 0x0222,
                 'title': "This effect simulates an organ sound",
                 #'dsp': 7.2000, 'dspmax': 1 / 6, 'dspmin': 16 / 100,
                 'parameters': [
                     {'name': "Upper", 'default': 70, 'max': 100},
                     {'name': "Lower", 'default': 80, 'max': 100},
                     {'name': "Dry", 'default': 80, 'max': 100},
                     {'name': "HPF", 'default': 3, 'max': 10},
                     {'name': "LPF", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x00100010: {'name': "Delay", 'category': "DELAY", 'order': 80, 'install': 0, 'ver': 0x0111,
                 'title': "This long delay has a maximum length of 4000 ms",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Time", 'default': 559, 'max': 4022,  # FIXME - Add time labels
                      'disp': {
                         'type':  "Time", 'min':  1, 'max': 4001,
                          'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3", "𝅘𝅥𝅯..",
                               "𝅘𝅥𝅮.", "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                               "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                               "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                               "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                               "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                               "𝅘𝅥𝅮  x8", "𝅘𝅥𝅮  x9",
                               "𝅘𝅥𝅮  x10", "𝅘𝅥𝅮  x11",
                               "𝅘𝅥𝅮  x12", "𝅘𝅥𝅮  x13",
                               "𝅘𝅥𝅮  x14", "𝅘𝅥𝅮  x15",
                               "𝅘𝅥𝅮  x16"]}},
                     {'name': "F.B", 'default': 30, 'max': 100},
                     {'name': "Mix", 'default': 70, 'max': 100},
                     {'name': "HiDMP", 'default': 10, 'max': 10},
                     {'name': "P-P", 'default': 0, 'max': 1, 'labels': ["MONO", "P-P"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x40600110: {'name': "CarbonDly", 'category': "DELAY", 'order': 81, 'install': 0, 'ver': 0x0123,
                 'title': "This analog delay sound is a model of the MXR Carbon Copy",
                 #'dsp': 4.4444, 'dspmax': 1 / 4, 'dspmin': 11 / 48,
                 'parameters': [
                     {'name': "DELAY", 'default': 387, 'max': 562, 'disp': 19},
                     {'name': "REGEN", 'default': 47, 'max': 100},
                     {'name': "MIX", 'default': 69, 'max': 100},
                     {'name': "MID", 'default': 1, 'max': 1, 'labels': ["OFF", "ON"]},
                     {'name': "WIDTH", 'default': 31, 'max': 50},
                     {'name': "SPEED", 'default': 28, 'max': 50},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                     {'name': "Sync", 'default': 0, 'max': 15,  # FIXME - Add time labels
                      'labels': ["OFF", "1/16", "1/12", "3/32", "1/8", "1/6", "3/16", "1/4", "3/8", "1/2", "3/4", "4/4",
                               "5/4", "6/4", "7/4", "8/4"]},
                 ]},
0x40000110: {'name': "StompDly", 'category': "DELAY", 'order': 82, 'install': 0, 'ver': 0x0111,
                 'title': "By turning the feedback up on this stomp-style delay, you can make it self-oscillate",
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "E.LVL", 'default': 30, 'max': 120},
                     {'name': "F.B", 'default': 20, 'max': 100},
                     {'name': "Time", 'default': 359, 'max': 599, 'disp': 1},
                     {'name': "Sync", 'default': 0, 'max': 15, # FIXME - Add time labels
                      'labels': ["OFF", "1/16", "1/12", "3/32", "1/8", "1/6", "3/16", "1/4", "3/8", "1/2", "3/4", "4/4",
                               "5/4", "6/4", "7/4", "8/4"]},
                     {'name': "Mode", 'default': 0, 'max': 1, 'labels': ["MONO", "STR"]},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                     {'name': "HiDMP", 'default': 5, 'max': 10},
                 ]},
0x00200010: {'name': "TapeEcho", 'category': "DELAY", 'order': 83, 'install': 0, 'ver': 0x0121,
                 'title': 'This effect simulates a tape echo. Changing the "Time" parameter changes the pitch of the echoes',
                 #'dsp': 12.4737, 'dspmax': 1 / 10, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Time", 'default': 559, 'max': 2014, 'disp': {'type':  "Time", 'min':  1, 'max': 2001, # FIXME - Add time labels
                                                                        'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3", "𝅘𝅥𝅯..",
                                                                               "𝅘𝅥𝅮.", "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                                                                               "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                                                                               "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                                                                               "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                                                                               "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                                                                               "𝅘𝅥𝅮  x8"]}},
                     {'name': "F.B", 'default': 64, 'max': 100},
                     {'name': "Mix", 'default': 56, 'max': 100},
                     {'name': "HiDMP", 'default': 5, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x40000010: {'name': "ReverseDL", 'category': "DELAY", 'order': 84, 'install': 0, 'ver': 0x0121,
                 'title': "This reverse delay is a long delay with a maximum length of 2000 ms",
                 #'dsp': 14.2628, 'dspmax': 1 / 12, 'dspmin': 1 / 20,
                 'parameters': [
                     {'name': "Time", 'default': 990, 'max': 2005, 'disp': {'type':  "Time", 'min':  10, 'max': 2001, # FIXME - Add time labels
                                                                        'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3", "𝅘𝅥𝅯..",
                                                                               "𝅘𝅥𝅮.", "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                                                                               "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                                                                               "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                                                                               "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                                                                               "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                                                                               "𝅘𝅥𝅮  x8"]}},
                     {'name': "F.B", 'default': 20, 'max': 100},
                     {'name': "Bal", 'default': 50, 'max': 100},
                     {'name': "HiDMP", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
    0x40200010: {'name': "MultiTapD", 'category': "DELAY", 'order': 85, 'install': 0, 'ver': 0x0122,
                 'title': "This effect produces several delay sounds with different delay times",
                 #'dsp': 10.7911, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Time", 'default': 2999, 'max': 3018, 'disp': {'type': "Time", 'min': 1, 'max': 3001,   # FIXME - Add time labels
                                                                             'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3",
                                                                                      "𝅘𝅥𝅯..", "𝅘𝅥𝅮.",
                                                                                      "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                                                                                      "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                                                                                      "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                                                                                      "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                                                                                      "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                                                                                      "𝅘𝅥𝅮  x8", "𝅘𝅥𝅮  x9",
                                                                                      "𝅘𝅥𝅮  x10", "𝅘𝅥𝅮  x11",
                                                                                      "𝅘𝅥𝅮  x12"]}},
                     {'name': "PTTRN", 'default': 1, 'max': 7, 'disp': 1},
                     {'name': "Mix", 'default': 20, 'max': 100},
                     {'name': "Tone", 'default': 10, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
    0x40600010: {'name': "FilterDly", 'category': "DELAY", 'order': 86, 'install': 0, 'ver': 0x0122,
                 'title': "This effect filters a delayed sound",
                 #'dsp': 10.7911, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Time", 'default': 499, 'max': 2014, 'disp': {'type': "Time", 'min': 1, 'max': 2001,  # FIXME - Add time labels
                                                                            'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3", "𝅘𝅥𝅯..",
                                                                                     "𝅘𝅥𝅮.", "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                                                                                     "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                                                                                     "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                                                                                     "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                                                                                     "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                                                                                     "𝅘𝅥𝅮  x8"]}},
                     {'name': "F.B", 'default': 50, 'max': 100},
                     {'name': "Mix", 'default': 90, 'max': 100},
                     {'name': "Rate", 'default': 6, 'max': 49, 'disp': 1},
                     {'name': "Depth", 'default': 100, 'max': 100},
                     {'name': "Reso", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00000110: {'name': "PitchDly", 'category': "DELAY", 'order': 87, 'install': 0, 'ver': 0x0122,
                 'title': "This effect applies pitch shift to a delayed sound",
                 #'dsp': 7.5224, 'dspmax': 1 / 6, 'dspmin': 16 / 100,
                 'parameters': [
                     {'name': "Time", 'default': 89, 'max': 1999, 'disp': 1},
                     {'name': "Pitch", 'default': 21, 'max': 30, 'labels': [
                         "-12", "-11", "-10", "-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1",
                         "-0.15", "-0.10", "-0.05", "0", "0.05", "0.10", "0.15",
                         "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"
                     ]},
                     {'name': "Mix", 'default': 80, 'max': 100},
                     {'name': "F.B", 'default': 80, 'max': 100},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
    0x00200110: {'name': "StereoDly", 'category': "DELAY", 'order': 88, 'install': 0, 'ver': 0x0122,
                 'title': "This stereo delay allows the left and right delay times to be set separately",
                 #'dsp': 10.7911, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "TimeL", 'default': 164, 'max': 2014, 'disp': {'type':  "Time", 'min':  1, 'max': 2001,  # FIXME - Add time labels
                                                                         'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3",
                                                                                "𝅘𝅥𝅯..", "𝅘𝅥𝅮.",
                                                                                "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                                                                                "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                                                                                "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                                                                                "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                                                                                "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                                                                                "𝅘𝅥𝅮  x8"]}},
                     {'name': "TimeR", 'default': 504, 'max': 2014, 'disp': {'type':  "Time", 'min':  1, 'max': 2001,  # FIXME - Add time labels
                                                                         'list': ["𝅘𝅥𝅯.", "𝅘𝅥𝅮  3",
                                                                                "𝅘𝅥𝅯..", "𝅘𝅥𝅮.",
                                                                                "𝅗𝅥. 3", "𝅘𝅥𝅮..",
                                                                                "𝅘𝅥𝅮 ", "𝅘𝅥𝅮 .",
                                                                                "𝅘𝅥𝅮  x2", "𝅘𝅥𝅮  x3",
                                                                                "𝅘𝅥𝅮  x4", "𝅘𝅥𝅮  x5",
                                                                                "𝅘𝅥𝅮  x6", "𝅘𝅥𝅮  x7",
                                                                                "𝅘𝅥𝅮  x8"]}},
                     {'name': "Mix", 'default': 100, 'max': 100},
                     {'name': "LchFB", 'default': 55, 'max': 100},
                     {'name': "RchFB", 'default': 37, 'max': 100},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "LchLv", 'default': 100, 'max': 100},
                     {'name': "RchLv", 'default': 100, 'max': 100},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00100012: {'name': "HD Hall", 'category': "REVERB", 'order': 89, 'install': 0, 'ver': 0x0111,
                 'title': "This is a dense hall reverb",
                 #'dsp': 2.3356, 'dspmax': 9 / 20, 'dspmin': 3 / 8,
                 'parameters': [
                     {'name': "PreD", 'default': 80, 'max': 199, 'disp': 1},
                     {'name': "Decay", 'default': 45, 'max': 100},
                     {'name': "Mix", 'default': 62, 'max': 100},
                     {'name': "LoDMP", 'default': 32, 'max': 100},
                     {'name': "HiDMP", 'default': 70, 'max': 100},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00200012: {'name': "Hall", 'category': "REVERB", 'order': 90, 'install': 0, 'ver': 0x0121,
                 'title': "This reverb effect simulates the acoustics of a concert hall",
                 #'dsp': 8.7273, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Decay", 'default': 9, 'max': 29, 'disp': 1},
                     {'name': "Tone", 'default': 5, 'max': 10},
                     {'name': "Mix", 'default': 46, 'max': 100},
                     {'name': "PreD", 'default': 48, 'max': 99, 'disp': 1},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00400012: {'name': "Room", 'category': "REVERB", 'order': 91, 'install': 0, 'ver': 0x0111,
                 'title': "This reverb effect simulates the acoustics of a room",
                 #'dsp': 10.7911, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Decay", 'default': 9, 'max': 29, 'disp': 1},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Mix", 'default': 60, 'max': 100},
                     {'name': "PreD", 'default': 4, 'max': 99, 'disp': 1},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
    0x00600012: {'name': "TiledRoom", 'category': "REVERB", 'order': 92, 'install': 0, 'ver': 0x0122,
                 'title': "This reverb effect simulates the acoustics of a tiled room",
                 #'dsp': 9.6000, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Decay", 'default': 19, 'max': 29, 'disp': 1},
                     {'name': "Tone", 'default': 4, 'max': 10},
                     {'name': "Mix", 'default': 46, 'max': 100},
                     {'name': "PreD", 'default': 9, 'max': 99, 'disp': 1},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x40200012: {'name': "Arena", 'category': "REVERB", 'order': 93, 'install': 0, 'ver': 0x0122,
                 'title': "This reverb effect simulates the acoustics of a large enclosure such as a sports arena",
                 #'dsp': 10.7911, 'dspmax': 1 / 10, 'dspmin': 1 / 15,
                 'parameters': [
                     {'name': "Decay", 'default': 14, 'max': 29, 'disp': 1},
                     {'name': "Tone", 'default': 7, 'max': 10},
                     {'name': "Mix", 'default': 56, 'max': 100},
                     {'name': "PreD", 'default': 89, 'max': 99, 'disp': 1},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00200112: {'name': "Plate", 'category': "REVERB", 'order': 94, 'install': 0, 'ver': 0x0113,
                 'title': "This simulates a plate reverb",
                 #'dsp': 3.4565, 'dspmax': 28 / 100, 'dspmin': 10 / 36,
                 'parameters': [
                     {'name': "PreD", 'default': 8, 'max': 199, 'disp': 1},
                     {'name': "Decay", 'default': 52, 'max': 100},
                     {'name': "Mix", 'default': 44, 'max': 100},
                     {'name': "Color", 'default': 58, 'max': 100},
                     {'name': "LoDMP", 'default': 97, 'max': 100},
                     {'name': "HiDMP", 'default': 95, 'max': 100},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                     {'name': "Level", 'default': 100, 'max': 150},
                 ]},
0x40000112: {'name': "Spring63", 'category': "REVERB", 'order': 95, 'install': 0, 'ver': 0x0123,
                 'title': "This spring reverb sound is modeled on a '63 Fender Reverb",
                 #'dsp': 2.6737, 'dspmax': 4 / 10, 'dspmin': 1 / 3,
                 'parameters': [
                     {'name': "DWELL", 'default': 35, 'max': 100},
                     {'name': "MIXER", 'default': 51, 'max': 100},
                     {'name': "TONE", 'default': 58, 'max': 100},
                     {'name': "LEVEL", 'default': 100, 'max': 150},
                 ]},
0x40600012: {'name': "Air", 'category': "REVERB", 'order': 96, 'install': 0, 'ver': 0x0122,
                 'title': "This effect reproduces the ambience of a room, to create spatial depth",
                 #'dsp': 15.1257, 'dspmax': 1 / 12, 'dspmin': 2 / 25,
                 'parameters': [
                     {'name': "Size", 'default': 19, 'max': 99, 'disp': 1},
                     {'name': "Tone", 'default': 8, 'max': 10},
                     {'name': "Mix", 'default': 60, 'max': 100},
                     {'name': "Ref", 'default': 5, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x40400012: {'name': "EarlyRef", 'category': "REVERB", 'order': 97, 'install': 0, 'ver': 0x0122,
                 'title': "This effect reproduces only the early reflections of reverb",
                 #'dsp': 7.4071, 'dspmax': 1 / 6, 'dspmin': 16 / 100,
                 'parameters': [
                     {'name': "Decay", 'default': 14, 'max': 29, 'disp': 1},
                     {'name': "Shape", 'default': 20, 'max': 20, 'disp': -10},
                     {'name': "Mix", 'default': 50, 'max': 100},
                     {'name': "Tone", 'default': 6, 'max': 10},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00400112: {'name': "ModReverb", 'category': "REVERB", 'order': 98, 'install': 0, 'ver': 0x0113,
                 'title': "This reverb generates fluctuating echoes",
                 #'dsp': 4.4893, 'dspmax': 1 / 4, 'dspmin': 1 / 5,
                 'parameters': [
                     {'name': "Depth", 'default': 38, 'max': 100},
                     {'name': "Decay", 'default': 19, 'max': 29, 'disp': 1},
                     {'name': "Mix", 'default': 45, 'max': 100},
                     {'name': "Rate", 'default': 19, 'max': 49, 'disp': 1},
                     {'name': "Tone", 'default': 6, 'max': 10},
                     {'name': "PreD", 'default': 29, 'max': 99, 'disp': 1},
                     {'name': "Level", 'default': 100, 'max': 150},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
0x00200312: {'name': "ParticleR", 'category': "REVERB", 'order': 99, 'install': 0, 'ver': 0x0103,
                 'title': "This unique complex reverb effect models the LINE6 M9 Particle Verb",
                 #'dsp': 1.7804, 'dspmax': 3 / 5, 'dspmin': 1 / 2,
                 'parameters': [
                     {'name': "DWELL", 'default': 40, 'max': 100},
                     {'name': "GAIN", 'default': 100, 'max': 100},
                     {'name': "MODE", 'default': 0, 'max': 2, 'labels': ["STBL", "CRTCL", "HZD"]},
                     {'name': "MIX", 'default': 60, 'max': 100},
                     {'name': "MONO", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                     {'name': "Tail", 'default': 0, 'max': 1, 'labels': ["OFF", "ON"]},
                 ]},
}
